name: Xcode - Build Archive

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build sideloading package for TrollStore
    runs-on: macos-13

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build ReveilHelper
        run: |
          xcodebuild clean build archive \
            -scheme ReveilHelper \
            -project Reveil.xcodeproj \
            -archivePath ReveilHelper.xcarchive \
            CODE_SIGNING_ALLOWED=NO SKIP_INSTALL=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Build Reveil
        run: |
          # Make sure ReveilHelper is in the PATH
          export PATH=$PWD/ReveilHelper.xcarchive/Products/usr/local/bin:$PATH
          
          # Check if ReveilHelper is available
          if ! command -v ReveilHelper &> /dev/null; then
            echo "ReveilHelper could not be found"
            exit 1
          fi

          # Build and archive Reveil
          xcodebuild clean build archive \
            -scheme Reveil \
            -project Reveil.xcodeproj \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath Reveil \
            CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package for sideloading
        run: |
          cd Reveil.xcarchive/Products/Applications
          codesign --remove-signature Reveil.app
          cd -
          cd Reveil.xcarchive/Products
          mv Applications Payload
          zip -qr reveil15.tipa Payload
          cd -
          mv Reveil.xcarchive/Products/reveil15.tipa .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: reveil
          path: |
            Reveil.xcarchive
            reveil15.tipa
            
      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: reveil15.tipa
          tag_name: rootless
          name: rootless
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
