name: Xcode - Build Archive (iOS 14)

on:
  push:
    branches: [ "rootful" ]
  pull_request:
    branches: [ "rootful" ]

env:
  MARKETING_VERSION: 1.4
  PATCH_VERSION: 1

jobs:
  build:
    name: Build sideloading package for TrollStore
    runs-on: macos-13

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.3.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build helper
        run: |
          xcodebuild clean build archive -scheme ReveilHelper -project Reveil.xcodeproj -archivePath ReveilHelper.xcarchive CODE_SIGNING_ALLOWED=NO

      - name: Build
        run: |
          PATH=$PWD/ReveilHelper.xcarchive/Products/usr/local/bin:$PATH xcodebuild clean build archive -scheme Reveil -project Reveil.xcodeproj -sdk iphoneos -destination 'generic/platform=iOS' -archivePath Reveil CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package for sideloading
        run: |
          cd Reveil.xcarchive/Products/Applications
          codesign --remove-signature Reveil.app
          cd -
          cd Reveil.xcarchive/Products
          mv Applications Payload
          zip -qr Reveil_${{ env.MARKETING_VERSION }}.tipa Payload
          cd -
          mv Reveil.xcarchive/Products/Reveil_${{ env.MARKETING_VERSION }}.tipa .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Reveil_${{ env.MARKETING_VERSION }}
          path: |
            Reveil.xcarchive
            Reveil_${{ env.MARKETING_VERSION }}.tipa
