name: Xcode - Build Archive

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build sideloading package for TrollStore
    runs-on: macos-13

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build helper
        run: |
          xcodebuild clean build archive -scheme ReveilHelper -project Reveil.xcodeproj -archivePath ReveilHelper.xcarchive CODE_SIGNING_ALLOWED=NO

      - name: Build
        run: |
          PATH=$PWD/ReveilHelper.xcarchive/Products/usr/local/bin:$PATH xcodebuild clean build archive -scheme Reveil -project Reveil.xcodeproj -sdk iphoneos -destination 'generic/platform=iOS' -archivePath Reveil CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package for sideloading
        run: |
          cd Reveil.xcarchive/Products/Applications
          codesign --remove-signature Reveil.app
          cd -
          cd Reveil.xcarchive/Products
          mv Applications Payload
          zip -qr reveil.tipa Payload
          cd -
          mv Reveil.xcarchive/Products/reveil.tipa .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: reveil
          path: |
            Reveil.xcarchive
            reveil.tipa
            
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          name: rootless
          body_path: CHANGELOG.md
          files: reveil.tipa
